# Generated by Django 4.1.5 on 2023-01-31 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Horror', 'HORROR'), ('Romance', 'ROMANCE'), ('Fantasy', 'FANTASY'), ('Scifi', 'SCIFI'), ('Education', 'EDUCATION'), ('Other', 'OTHER')], default='Other', max_length=20)),
                ('release_year', models.DateTimeField(verbose_name='%y')),
                ('number_in_inventory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_returned', models.BooleanField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.customer')),
            ],
        ),
    ]
