# Generated by Django 4.1.5 on 2023-02-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.book'),
        ),
    ]
