# Generated by Django 4.1.5 on 2023-02-27 21:40

import creditcards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='Full name')),
                ('address1', models.CharField(max_length=1024, null=True, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='Card number')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='Card expiry')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='Card security code')),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crust_size', models.CharField(choices=[('normal', 'Normal'), ('thin', 'Thin'), ('thick', 'Thick'), ('gluten free', 'Gluten Free')], max_length=20)),
                ('topping', models.CharField(max_length=1000)),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cheese')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.customer')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.sauce')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.size')),
            ],
        ),
    ]
