# Generated by Django 4.1.5 on 2023-01-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('someattribute', models.TextField()),
                ('another_field', models.CharField(max_length=10)),
                ('some_date', models.DateField()),
                ('an_integer', models.IntegerField()),
                ('a_decimal', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
