# Generated by Django 4.1.5 on 2023-01-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='a_decimal',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='someattribute',
            new_name='Synopsis',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='some_date',
            new_name='Year',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='an_integer',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='another_field',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Author',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Title',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
