# Generated by Django 4.1.5 on 2023-01-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_alter_mymodel_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Book',
        ),
    ]
