# Generated by Django 4.1.5 on 2023-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_rename_author_book_author_rename_price_book_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
