# Generated by Django 4.1.5 on 2023-01-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0009_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Horror', 'HORROR'), ('Romance', 'ROMANCE'), ('Fantasy', 'FANTASY'), ('Humour and satire', 'HUMOUR AND SATIRE'), ('Education', 'EDUCATION'), ('Other', 'OTHER')], default='OTHER', max_length=20),
        ),
    ]
