# Generated by Django 4.1.5 on 2023-01-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0011_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('horror', 'HORROR'), ('romance', 'ROMANCE'), ('fantasy', 'FANTASY'), ('humour and satire', 'HUMOUR AND SATIRE'), ('education', 'EDUCATION'), ('other', 'OTHER')], default='Other', max_length=20),
        ),
    ]
